OBJS-$(CONFIG_VVC_DECODER)             += x86/vvc/vvcdsp_init.o
X86ASM-OBJS-$(CONFIG_VVC_DECODER)      += x86/vvc/vvc_alf.o                 \
                                          x86/vvc/vvc_inter.o				\
                                          x86/vvc/vvc_sao.o                 \
                                          x86/vvc/vvc_sao_10bit.o           \
                                          x86/vvc/vvc_itx.o
