clean::
	$(RM) $(CLEANSUFFIXES:%=libavcodec/vvc/%)

OBJS-$(CONFIG_VVC_DECODER)          +=  vvc/vvcdec.o            \
                                        vvc/vvc_data.o          \
                                        vvc/vvc_ps.o            \
