OBJS-$(CONFIG_VVCPARSE)             += 	vvc/vvc_ps.o			\
										vvc/vvc_data.o			\
										h2645data.o 			\
										h2645_parse.o 			\
										h2645_vui.o
OBJS-$(CONFIG_VVC_DECODER)          += 	vvc/vvcdec.o			\
									 	vvc/vvc_executor.o		\
										vvc/vvc_thread.o		\
										vvc/vvc_cabac.o			\
										vvc/vvc_ctu.o			\
										vvc/vvcdsp.o			\
										vvc/vvc_itx_1d.o		\
										vvc/vvc_intra.o			\
										vvc/vvc_inter.o			\
										vvc/vvc_mvs.o			\
										vvc/vvc_refs.o			\
										vvc/vvc_filter.o
