name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  FFMPEG_PATH: FFmpeg/ffmpeg

jobs:

  linux:
    name: Linux.${{ matrix.compiler.compiler }}
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - { compiler: GNU,  CC: gcc }
          - { compiler: LLVM, CC: clang}

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure
      run: ./configure --cc=${{ matrix.compiler.CC }} --disable-asm --enable-ffmpeg --disable-everything --enable-decoder=vvc --enable-parser=vvc --enable-demuxer=vvc --enable-protocol=file,pipe --enable-encoder=rawvideo --enable-muxer=rawvideo,md5

    - name: Build
      run: make -j

    - name: Download Bitstream
      run: cd .. && git clone https://github.com/ffvvc/tests.git tests

    - name: Unit test
      run: cd .. && python3 tests/tools/ffmpeg.py tests/conformance/passed

    - name: Negative test
      run: cd .. && python3 tests/tools/ffmpeg.py tests/conformance/failed || true

  windows:
    name: Windows.MSVC
    runs-on: windows-latest

    steps:
    - name: Get FFVS-Project-Generator
      run: Invoke-WebRequest -Uri https://github.com/ShiftMediaProject/FFVS-Project-Generator/releases/download/1.11.6/FFVS-Project-Generator_1.11.6_x64.zip -OutFile FFVS-Project-Generator.zip; Expand-Archive FFVS-Project-Generator.zip

    - name: Get repository
      uses: actions/checkout@v3
      with:
        path: main

    - name: Build
      run: .\FFVS-Project-Generator\project_generate.exe --enable-gpl --enable-version3 --disable-bzlib --disable-iconv --disable-zlib --disable-lzma --disable-sdl --toolchain=msvc --rootdir=main

    - name: Download Bitstream
      uses: actions/checkout@v3
      with:
        repository: ffvvc/tests
        path: tests

    - name: Unit test
      run: python3 tests/tools/ffmpeg.py tests/conformance/passed

    - name: Negative test
      run: python3 tests/tools/ffmpeg.py tests/conformance/failed || true
